app:
  name: "ProjMatrix"
  environment: "development"
  port: 8080

logging:
  level: "info"
  format: "json"
  file: "logs/app.log"

db:
  dsn: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"